Applying update to generators
bitovi/github-actions-deploy-stackstorm pull request #30
Opened 2023-01-06 15:25 UTC by PhillypHenning

2023-01-06 16:13 UTC, LeoDiazL approved these changes
Looking good

2023-01-09 18:07 UTC, armab requested changes
A brief description for the PR would be nice to have a better understanding as I had to spend a few cycles to understand the high-level idea first.
I understand some refactoring is happening and left a couple of comments.

2023-01-09 18:07 UTC, armab commented on operations/_scripts/generate/generate_buckets_identifiers.sh
> +function generateIdentifiers () {
Same as for the other function, naming and description would be nice to haves.

And quickly looking at it, I didn't understand what kind of Identifiers the function generates.
`generate_bucket_names()` or `generate_bucket_identifiers` perhaps would be more clear?

2023-01-09 21:16 UTC, PhillypHenning commented
Gotcha - Sorry about that @armab, this was work that was ported over from an upgrade to the docker-to-ec2. (Hence why I was pushing for a commons last week)

I'll post up some cleanup shortly

2023-01-09 21:26 UTC, armab approved these changes
Thanks!

2023-01-11 15:53 UTC, merged